### ISSUE TITLE
MoM 1

### ISSUE THREAD

**Issue by schedutron** [Ideas-Labs/S-Koo-L#3]
* Compare REST and GraphQL for our usecase
*  Think on database schema
        - Teacher: ID, FirstName, LastName, DOB, email, [subjects...], [standards...]
        - School: ID, Name, Address, Board
        - Subject: ID, Name
        - User: (principal for now) ID, Name, Email, Password, (Role) <- optional

**Comment by ParthS007** [comment]
Created PR #4
